/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */

export type AlertType = typeof AlertType[keyof typeof AlertType];


export const AlertType = {
  speed: 'speed',
  zone: 'zone',
  system: 'system',
} as const;
