/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */
import type { AlertType } from './alertType';

export interface Alert {
  id: number;
  type: AlertType;
  title: string;
  detail: string;
  createdAt: string;
  acknowledged: boolean;
}
