/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */
export type AlertType = typeof AlertType[keyof typeof AlertType];
export declare const AlertType: {
    readonly speed: "speed";
    readonly zone: "zone";
    readonly system: "system";
};
//# sourceMappingURL=alertType.d.ts.map