/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */
export type AnalysisStatus = typeof AnalysisStatus[keyof typeof AnalysisStatus];
export declare const AnalysisStatus: {
    readonly ready: "ready";
    readonly analyzing: "analyzing";
    readonly completed: "completed";
    readonly stopped: "stopped";
};
//# sourceMappingURL=analysisStatus.d.ts.map