/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalysisStatus } from './analysisStatus';

export interface AnalysisSession {
  status: AnalysisStatus;
  /**
     * @minimum 0
     * @maximum 100
     */
  progress: number;
  source: string;
  /** @nullable */
  startedAt: string | null;
  /** @nullable */
  completedAt: string | null;
}
