/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * Returns the current analysis session, summary metrics, flow counts, tracked objects, and recent alerts.
 * @summary Get the live monitoring overview
 */
export const getMonitoringOverviewResponseSessionProgressMin = 0;
export const getMonitoringOverviewResponseSessionProgressMax = 100;



export const GetMonitoringOverviewResponse = zod.object({
  "session": zod.object({
  "status": zod.enum(['ready', 'analyzing', 'completed', 'stopped']),
  "progress": zod.number().int().min(getMonitoringOverviewResponseSessionProgressMin).max(getMonitoringOverviewResponseSessionProgressMax),
  "source": zod.string(),
  "startedAt": zod.string().nullable(),
  "completedAt": zod.string().nullable()
}),
  "stats": zod.object({
  "vehicles": zod.number().int(),
  "objects": zod.number().int(),
  "averageSpeed": zod.number().int(),
  "fps": zod.number().int()
}),
  "flow": zod.object({
  "incoming": zod.number().int(),
  "outgoing": zod.number().int()
}),
  "objects": zod.array(zod.object({
  "id": zod.number().int(),
  "className": zod.string(),
  "confidence": zod.number(),
  "speed": zod.number().int(),
  "zone": zod.string(),
  "direction": zod.string(),
  "lastSeen": zod.string()
})),
  "alerts": zod.array(zod.object({
  "id": zod.number().int(),
  "type": zod.enum(['speed', 'zone', 'system']),
  "title": zod.string(),
  "detail": zod.string(),
  "createdAt": zod.string(),
  "acknowledged": zod.boolean()
})),
  "updatedAt": zod.string()
})


/**
 * @summary Start a traffic analysis session
 */



export const StartAnalysisBody = zod.object({
  "source": zod.string().min(1).optional()
})

export const startAnalysisResponseProgressMin = 0;
export const startAnalysisResponseProgressMax = 100;



export const StartAnalysisResponse = zod.object({
  "status": zod.enum(['ready', 'analyzing', 'completed', 'stopped']),
  "progress": zod.number().int().min(startAnalysisResponseProgressMin).max(startAnalysisResponseProgressMax),
  "source": zod.string(),
  "startedAt": zod.string().nullable(),
  "completedAt": zod.string().nullable()
})


/**
 * @summary Stop the active traffic analysis session
 */
export const StopAnalysisBody = zod.object({
  "reason": zod.string().optional()
})

export const stopAnalysisResponseProgressMin = 0;
export const stopAnalysisResponseProgressMax = 100;



export const StopAnalysisResponse = zod.object({
  "status": zod.enum(['ready', 'analyzing', 'completed', 'stopped']),
  "progress": zod.number().int().min(stopAnalysisResponseProgressMin).max(stopAnalysisResponseProgressMax),
  "source": zod.string(),
  "startedAt": zod.string().nullable(),
  "completedAt": zod.string().nullable()
})


