/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * Returns the current analysis session, summary metrics, flow counts, tracked objects, and recent alerts.
 * @summary Get the live monitoring overview
 */
export declare const getMonitoringOverviewResponseSessionProgressMin = 0;
export declare const getMonitoringOverviewResponseSessionProgressMax = 100;
export declare const GetMonitoringOverviewResponse: zod.ZodObject<{
    session: zod.ZodObject<{
        status: zod.ZodEnum<["ready", "analyzing", "completed", "stopped"]>;
        progress: zod.ZodNumber;
        source: zod.ZodString;
        startedAt: zod.ZodNullable<zod.ZodString>;
        completedAt: zod.ZodNullable<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        status: "ready" | "analyzing" | "completed" | "stopped";
        progress: number;
        source: string;
        startedAt: string | null;
        completedAt: string | null;
    }, {
        status: "ready" | "analyzing" | "completed" | "stopped";
        progress: number;
        source: string;
        startedAt: string | null;
        completedAt: string | null;
    }>;
    stats: zod.ZodObject<{
        vehicles: zod.ZodNumber;
        objects: zod.ZodNumber;
        averageSpeed: zod.ZodNumber;
        fps: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        vehicles: number;
        objects: number;
        averageSpeed: number;
        fps: number;
    }, {
        vehicles: number;
        objects: number;
        averageSpeed: number;
        fps: number;
    }>;
    flow: zod.ZodObject<{
        incoming: zod.ZodNumber;
        outgoing: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        incoming: number;
        outgoing: number;
    }, {
        incoming: number;
        outgoing: number;
    }>;
    objects: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        className: zod.ZodString;
        confidence: zod.ZodNumber;
        speed: zod.ZodNumber;
        zone: zod.ZodString;
        direction: zod.ZodString;
        lastSeen: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        className: string;
        confidence: number;
        speed: number;
        zone: string;
        direction: string;
        lastSeen: string;
    }, {
        id: number;
        className: string;
        confidence: number;
        speed: number;
        zone: string;
        direction: string;
        lastSeen: string;
    }>, "many">;
    alerts: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        type: zod.ZodEnum<["speed", "zone", "system"]>;
        title: zod.ZodString;
        detail: zod.ZodString;
        createdAt: zod.ZodString;
        acknowledged: zod.ZodBoolean;
    }, "strip", zod.ZodTypeAny, {
        type: "speed" | "zone" | "system";
        id: number;
        title: string;
        detail: string;
        createdAt: string;
        acknowledged: boolean;
    }, {
        type: "speed" | "zone" | "system";
        id: number;
        title: string;
        detail: string;
        createdAt: string;
        acknowledged: boolean;
    }>, "many">;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    session: {
        status: "ready" | "analyzing" | "completed" | "stopped";
        progress: number;
        source: string;
        startedAt: string | null;
        completedAt: string | null;
    };
    stats: {
        vehicles: number;
        objects: number;
        averageSpeed: number;
        fps: number;
    };
    objects: {
        id: number;
        className: string;
        confidence: number;
        speed: number;
        zone: string;
        direction: string;
        lastSeen: string;
    }[];
    flow: {
        incoming: number;
        outgoing: number;
    };
    alerts: {
        type: "speed" | "zone" | "system";
        id: number;
        title: string;
        detail: string;
        createdAt: string;
        acknowledged: boolean;
    }[];
    updatedAt: string;
}, {
    session: {
        status: "ready" | "analyzing" | "completed" | "stopped";
        progress: number;
        source: string;
        startedAt: string | null;
        completedAt: string | null;
    };
    stats: {
        vehicles: number;
        objects: number;
        averageSpeed: number;
        fps: number;
    };
    objects: {
        id: number;
        className: string;
        confidence: number;
        speed: number;
        zone: string;
        direction: string;
        lastSeen: string;
    }[];
    flow: {
        incoming: number;
        outgoing: number;
    };
    alerts: {
        type: "speed" | "zone" | "system";
        id: number;
        title: string;
        detail: string;
        createdAt: string;
        acknowledged: boolean;
    }[];
    updatedAt: string;
}>;
/**
 * @summary Start a traffic analysis session
 */
export declare const StartAnalysisBody: zod.ZodObject<{
    source: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    source?: string | undefined;
}, {
    source?: string | undefined;
}>;
export declare const startAnalysisResponseProgressMin = 0;
export declare const startAnalysisResponseProgressMax = 100;
export declare const StartAnalysisResponse: zod.ZodObject<{
    status: zod.ZodEnum<["ready", "analyzing", "completed", "stopped"]>;
    progress: zod.ZodNumber;
    source: zod.ZodString;
    startedAt: zod.ZodNullable<zod.ZodString>;
    completedAt: zod.ZodNullable<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "ready" | "analyzing" | "completed" | "stopped";
    progress: number;
    source: string;
    startedAt: string | null;
    completedAt: string | null;
}, {
    status: "ready" | "analyzing" | "completed" | "stopped";
    progress: number;
    source: string;
    startedAt: string | null;
    completedAt: string | null;
}>;
/**
 * @summary Stop the active traffic analysis session
 */
export declare const StopAnalysisBody: zod.ZodObject<{
    reason: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    reason?: string | undefined;
}, {
    reason?: string | undefined;
}>;
export declare const stopAnalysisResponseProgressMin = 0;
export declare const stopAnalysisResponseProgressMax = 100;
export declare const StopAnalysisResponse: zod.ZodObject<{
    status: zod.ZodEnum<["ready", "analyzing", "completed", "stopped"]>;
    progress: zod.ZodNumber;
    source: zod.ZodString;
    startedAt: zod.ZodNullable<zod.ZodString>;
    completedAt: zod.ZodNullable<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "ready" | "analyzing" | "completed" | "stopped";
    progress: number;
    source: string;
    startedAt: string | null;
    completedAt: string | null;
}, {
    status: "ready" | "analyzing" | "completed" | "stopped";
    progress: number;
    source: string;
    startedAt: string | null;
    completedAt: string | null;
}>;
//# sourceMappingURL=api.d.ts.map