/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */
import type { Alert } from './alert';
import type { AnalysisSession } from './analysisSession';
import type { FlowCounts } from './flowCounts';
import type { MonitoringStats } from './monitoringStats';
import type { TrackedObject } from './trackedObject';
export interface MonitoringOverview {
    session: AnalysisSession;
    stats: MonitoringStats;
    flow: FlowCounts;
    objects: TrackedObject[];
    alerts: Alert[];
    updatedAt: string;
}
//# sourceMappingURL=monitoringOverview.d.ts.map