/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * VisionGuard traffic monitoring API
 * OpenAPI spec version: 0.1.0
 */

export interface TrackedObject {
  id: number;
  className: string;
  confidence: number;
  speed: number;
  zone: string;
  direction: string;
  lastSeen: string;
}
